"""empty message

Revision ID: 035255683f03
Revises: a6a83a750405
Create Date: 2018-12-28 09:16:07.666580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '035255683f03'
down_revision = 'a6a83a750405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_infection_deck')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_infection_deck',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cards_in_deck', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('cards_discarded', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game_info.id'], name='game_infection_deck_game_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='game_infection_deck_pkey')
    )
    # ### end Alembic commands ###
