"""empty message

Revision ID: 31052672b3d3
Revises: 035255683f03
Create Date: 2018-12-28 09:34:51.784997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31052672b3d3'
down_revision = '035255683f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_infection_deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('reshuffled_on_top', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('current_discard_pile', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('cards_removed_from_deck', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_infection_deck')
    # ### end Alembic commands ###
