"""empty message

Revision ID: 3ecd7a486529
Revises: 
Create Date: 2018-11-23 11:39:53.634972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ecd7a486529'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_player_role', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game_player_role', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game_player_role', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_player_role', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game_player_role', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game_player_role', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
