"""empty message

Revision ID: a6a83a750405
Revises: c36c2bad3bce
Create Date: 2018-12-16 11:38:11.637095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a83a750405'
down_revision = 'c36c2bad3bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('has_research_station', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('uninfected', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('i_one', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('i_two', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('i_three', sa.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_infection_deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('cards_in_deck', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('cards_discarded', sa.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_player_deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('cards_in_deck', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('cards_in_hand', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('cards_discarded', sa.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_player_deck')
    op.drop_table('game_infection_deck')
    op.drop_table('game_cities')
    # ### end Alembic commands ###
