"""empty message

Revision ID: b3204cff7022
Revises: 36e93ef4622c
Create Date: 2018-12-13 19:01:39.243611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3204cff7022'
down_revision = '36e93ef4622c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('x_rat_key', sa.Integer(), nullable=True),
    sa.Column('y_rat_key', sa.Integer(), nullable=True),
    sa.Column('x_rat', sa.Float(precision=2), nullable=True),
    sa.Column('y_rat', sa.Float(precision=2), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('connections', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infection_deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('desciption', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_deck')
    op.drop_table('infection_deck')
    op.drop_table('cities')
    # ### end Alembic commands ###
