"""empty message

Revision ID: c36c2bad3bce
Revises: dde12f47d5ce
Create Date: 2018-12-15 14:20:34.102509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c36c2bad3bce'
down_revision = 'dde12f47d5ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('x_rat_key', sa.Integer(), nullable=True),
    sa.Column('y_rat_key', sa.Integer(), nullable=True),
    sa.Column('x_rat', sa.Float(precision=2), nullable=True),
    sa.Column('y_rat', sa.Float(precision=2), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('connections', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('jsonb_cities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jsonb_cities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('x_rat_key', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('y_rat_key', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('x_rat', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('y_rat', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('connections', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='jsonb_cities_pkey')
    )
    op.drop_table('cities')
    # ### end Alembic commands ###
